### ISSUE TITLE
Mining 3Dcoin blocks rejected

### ISSUE THREAD

**Issue by goodthebest** [BlockchainTechLLC/3dcoin#7]
Hi, I've been trying to mine 3dcoin on yiimp software but blocks somehow being rejected. I keep getting error rpc do call 127.0.0.1:port 404 block rejected. 

Does that mean only you can mine on MN wallet? If we do not have a MN we cannot setup a pool for mining? I used your yiimp repo that's for Keccakd. Please advise how can I fix this mining problem.

**Comment by BlockchainTechLLC** [comment]
Mining pools are no longer supported after v.0.14, the new validation algorithm is [Proof of Sync](https://github.com/BlockchainTechLLC/3dcoin/wiki/Proof-of-sync)
